version: "2"

issues:
  fix: true

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unconvert
    - prealloc
    - misspell

    #    - gosec
    #    - unused
    #    - revive
    #    - godox

  exclusions:
    paths:
      - vendor
      - third_party$
      - builtin$
      - proto

formatters:
  enable:
    - goimports
    - gofmt
    - gci
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/pubgo/protobuild
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
        - pattern: 'α[β:len(α)]'
          replacement: 'α[β:]'
        - pattern: 'α[:len(α)]'
          replacement: 'α'
        - pattern: 'make(map[α]β, 0)'
          replacement: 'make(map[α]β)'
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/pubgo/protobuild)

  exclusions:
    paths:
      - vendor
      - proto
