builds:
  - main: ./main.go
    id: protobuild
    binary: protobuild
    skip: false
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
  - main: ./cmd/protoc-gen-retag/main.go
    id: protoc-gen-retag
    binary: protoc-gen-retag
    skip: false
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    format: binary
report_sizes: true
