builds:
  - main: ./main.go
    id: protobuild
    binary: protobuild
    skip: false
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X 'github.com/pubgo/funk/version.version=v{{ .Version }}'
      - -X 'github.com/pubgo/funk/version.project=protobuild'
      - -X 'github.com/pubgo/funk/version.buildTime={{ .CommitDate }}'
      - -X 'github.com/pubgo/funk/version.commitID={{ .ShortCommit }}'
  - main: ./cmd/protoc-gen-retag/main.go
    id: protoc-gen-retag
    binary: protoc-gen-retag
    skip: false
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    name_template: >-
      {{ .Binary }}-
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
report_sizes: true
