builds:
  - main: ./main.go
    id: protobuild
    binary: protobuild
    skip: false
    goos:
      - linux
      - darwin
      - windows
    ldflags:
      - -X 'github.com/pubgo/protobuild/version.Version={{ .Version }}'
archives:
  - name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    format: binary
report_sizes: true
