builds:
  - main: ./main.go
    id: protobuild
    binary: protobuild
    skip: false
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags:
      - -X 'github.com/pubgo/protobuild/version.Version={{ .Version }}'
  - main: ./cmd/protoc-gen-retag/main.go
    id: protoc-gen-retag
    binary: protoc-gen-retag
    skip: false
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
archives:
  - name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
report_sizes: true
