builds:
  - main: ./main.go
    id: protobuild
    binary: protobuild
    skip: false
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X 'github.com/pubgo/funk/version.version=v{{ .Version }}'
      - -X 'github.com/pubgo/funk/version.project=protobuild'
      - -X 'github.com/pubgo/funk/version.buildTime={{ .CommitDate }}'
      - -X 'github.com/pubgo/funk/version.commitID={{ .ShortCommit }}'
archives:
  - name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    format: binary
report_sizes: true
