# https://taskfile.dev

version: '3'

vars:
  PROJECT: protobuild
  BASE: github.com/pubgo/protobuild
  TAG:
    sh: git describe --abbrev=0 --tags 2>/dev/null || echo "v0.0.0"
  VERSION:
    sh: git tag --sort=committerdate | tail -n 1 || echo "v0.0.0"
  BUILD_TIME:
    sh: date "+%F %T"
  COMMIT_ID:
    sh: git rev-parse --short=8 HEAD
  LDFLAGS: >-
    -ldflags "
    -X '{{.BASE}}/version.BuildTime={{.BUILD_TIME}}'
    -X '{{.BASE}}/version.CommitID={{.COMMIT_ID}}'
    -X '{{.BASE}}/version.Version={{.VERSION}}'
    -X '{{.BASE}}/version.Tag={{.TAG}}'
    -X '{{.BASE}}/version.Project={{.PROJECT}}'
    -X '{{.BASE}}/version.Data=hello'
    "

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the binary
    cmds:
      - go build {{.LDFLAGS}} -mod vendor -v -o main *.go
    sources:
      - "**/*.go"
    generates:
      - main

  install:
    desc: Install the binary to $GOPATH/bin
    cmds:
      - go install {{.LDFLAGS}} -mod vendor -v .

  vet:
    desc: Run go vet and format code
    cmds:
      - go vet ./...
      - gofumpt -l -w -extra .

  generate:
    desc: Run go generate
    cmds:
      - go generate ./...

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run --timeout 3m0s -v

  test:
    desc: Run tests
    cmds:
      - go test ./...

  test:coverage:
    desc: Run tests with coverage
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f main
      - rm -f coverage.out coverage.html

  mod:tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  mod:vendor:
    desc: Vendor dependencies
    cmds:
      - go mod vendor

  proto:vendor:
    desc: Vendor proto dependencies
    cmds:
      - go run . vendor

  proto:gen:
    desc: Generate protobuf code
    cmds:
      - go run . gen

  proto:lint:
    desc: Lint proto files
    cmds:
      - go run . lint

  proto:format:
    desc: Format proto files
    cmds:
      - go run . format

  proto:deps:
    desc: Show proto dependencies
    cmds:
      - go run . deps

  proto:clean:
    desc: Clean proto cache
    cmds:
      - go run . clean

  release:dry:
    desc: Dry run release with goreleaser
    cmds:
      - goreleaser release --snapshot --clean

  all:
    desc: Run vet, lint, test, and build
    cmds:
      - task: vet
      - task: lint
      - task: test
      - task: build
