// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// - protoc-gen-lava v0.1.0
// - protoc          v3.19.4
// source: retag/retag.proto

package retagpb

import grpc "google.golang.org/grpc"

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TagModel gen from github.com/pubgo/protobuild/pkg/retag.Tag
type TagModel struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

func (m *TagModel) ToProto() *Tag {
	if m == nil {
		return nil
	}

	var x = new(Tag)
	x.Name = m.Name

	x.Value = m.Value

	return x
}
func (x *Tag) ToModel() *TagModel {
	if x == nil {
		return nil
	}

	var m = new(TagModel)
	m.Name = x.Name

	m.Value = x.Value

	return m
}
