// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// - protoc-gen-lava v0.1.0
// - protoc          v3.19.4
// source: orm/model.proto

package ormpb

import (
	grpc "google.golang.org/grpc"
	"time"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ModelModel gen from github.com/pubgo/protobuild/pkg/orm.Model
type ModelModel struct {
	Id        uint64               `gorm:"primary_key" json:"id"`
	CreatedAt int64                `json:"created_at"`
	UpdatedAt int64                `json:"updated_at"`
	DeletedAt int64                `gorm:"index" json:"deleted_at"`
	Test_1    []string             `json:"test_1"`
	Test_2    *string              `json:"test_2"`
	Test_3    map[string]time.Time `json:"test_3"`
	Test_4    map[string]*Protobuf `json:"test_4"`
}

func (m ModelModel) ToProto() Model {}
